### ISSUE TITLE
When opening in a invite link, if guests are not enabled and registration is disabled, automatically redirect to login

### ISSUE THREAD

**Issue by felipecrs** [StevenWeathers/thunderdome-planning-poker#343]
And return back to the game from the invite link after logging in for a smooth joining experience.

**Comment by StevenWeathers** [comment]
This should already be functioning in this manner

**Comment by felipecrs** [comment]
I'm running 2.17, let me update and try again, if it does not work I will record a video.

**Comment by StevenWeathers** [comment]
I just tested it, if your attempt to login failed (bad password/user) it would redirect to `/login` removing the game ID, I've pushed a fix with 2.18.4 that resolves this particular scenario.  I was however able to successfully login and be redirected to the game with both registration and allow guest disabled.

**Comment by felipecrs** [comment]
Awesome, may I'm erroring my password too much. I tested both cases with 2.18.4 and now it's perfect. Thank you!

**Comment by felipecrs** [comment]
Hey @StevenWeathers, I would like to say that this issue is back (I'm testing with 2.25.1). Here is what happens:

1. My config looks like following:

```yaml
http:
    domain: <redacted>
    path_prefix: /poker
  db:
    host: thunderdome-planning-poker-postgresql
    port: 5432
    user: thunderdome
    pass: <redacted>
    name: thunderdome
  analytics:
    enabled: false
  smtp:
    enabled: false
  config:
    friendly_ui_verbs: true
    show_warrior_rank: true
    allow_guests: false
    allow_registration: false
    organizations_enabled: false
    require_teams: true
    allowedPointValues: [0, "1/2", 1, 2, 3, 4, 5, 8, 13, 15, 20, 30, 40, 60, 100, "?"]
    defaultPointValues: [0, "1/2", 1, 2, 3, 4, 5, 8, 13, 15, 20, 30, 40, 60, 100, "?"]
  admin:
    email: <redacted>
  auth:
    method: ldap
    ldap:
      url: <redacted>
      use_tls: false
      bindname: <redacted>
      bindpass:
      basedn: <redacted>
      filter: (&(objectClass=person)(mail=%s))
      mail_attr: mail
      cn_attr: <redacted>
```

2. When I open a link like the following:

```
https://<redacted>/poker/game/e0dd24b4-5175-4313-b0e0-76a130bdb7ba
```

3. The page redirects me to:

```
https://<redacted>/poker/register/battle/e0dd24b4-5175-4313-b0e0-76a130bdb7ba
```

![image](https://user-images.githubusercontent.com/29582865/197630486-80bb23c3-57e2-4b60-aa68-d60c218db52c.png)

I believe it was supposed to redirect me directly to:

```
https://<redacted>/poker/login/battle/e0dd24b4-5175-4313-b0e0-76a130bdb7ba
```

Instead of the register page.

**Comment by StevenWeathers** [comment]
The code for this hasn't really changed however I'm making a small change to the web socket handler for unauthorized as it wasn't using the same condition.
